version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx_img
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
    networks:
      - inception
  mariadb:
    container_name: mariadb
    image: mariadb_img
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    restart: always
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: wordpress_img
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
    restart: always
    networks:
      - inception

networks:
  inception:
    name: inception_net
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aelkhali/data/mariadb
  wordpress_data:
    name: wordpress_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aelkhali/data/wordpress
