version: '3.8'

services:
  mariadb:
    restart: always
    build: ./requirements/mariadb
    container_name: mariadb_container
    image: mariadb
    env_file:
        ./.env
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    restart: always
    depends_on:
        - mariadb
    build: ./requirements/wordpress
    container_name: wordpress_container
    image: wordpress
    env_file:
        ./.env
    volumes:
      - wordpress_data:/var/www/html/wordpress

  nginx:
    restart: always
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    container_name: nginx_container
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html/wordpress
  






volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/aelkhali/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aelkhali/data/mysql
  website:

networks:
  default: