version: "3.8"
services:

  nginx:
    container_name: nginx
    build: ./srcs/requirements/nginx/Dockerfile
    volumes:
      - wordpress:/var/www/html;
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    restrat: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb/Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    env-file:
      - .env
    restrat: always
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./srcs/requirements/wordpress/Dockerfile
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    env-file:
      - .env
    restrat: always
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/aelkhali/data/mariadb
  wordpress:
    driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/aelkhali/data/wordpress