version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
    networks:
      - inception
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    restart: always
    networks:
      - inception
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
    restart: always
    networks:
      - inception
  adminer:
    container_name: adminer
    image: adminer
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
  website:
    container_name: website
    image: website
    build:
      context: requirements/bonus/website
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    restart: always
  cadvisor:
    container_name: cadvisor
    image: cadvisor
    build:
      context: requirements/bonus/cadvisor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aelkhali/data/mariadb
  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aelkhali/data/wordpress

